"""Convert native Blueprint graph data into concise agent-facing logic."""

from __future__ import annotations

from copy import deepcopy
from typing import Any


def _compact_graph(graph: dict[str, Any]) -> dict[str, Any] | None:
    native_nodes = graph.get("nodes", [])
    flow_nodes = [
        node
        for node in native_nodes
        if any(pin.get("links") for pin in node.get("pins", []))
    ]
    if not flow_nodes:
        return None

    node_ids = {node["id"]: f"n{index}" for index, node in enumerate(flow_nodes, 1)}
    nodes = []
    connections = []

    for native_node in flow_nodes:
        operation = native_node.get("operation", {})
        node = {
            "id": node_ids[native_node["id"]],
            "name": native_node.get("title", ""),
            "kind": operation.get("kind", "event"),
        }
        for field in ("function", "owner", "variable"):
            if operation.get(field):
                node[field] = operation[field]

        inputs = {}
        for pin in native_node.get("pins", []):
            if (
                pin.get("direction") == "input"
                and not pin.get("links")
                and not pin.get("hidden")
                and not pin.get("default_matches_autogenerated", True)
            ):
                value = (
                    pin.get("default_value")
                    or pin.get("default_object")
                    or pin.get("default_text")
                )
                if value:
                    inputs[pin.get("name", "")] = value
        if inputs:
            node["inputs"] = inputs
        nodes.append(node)

        for pin in native_node.get("pins", []):
            if pin.get("direction") != "output":
                continue
            for link in pin.get("links", []):
                target_node_id = link.get("node_id")
                target_id = node_ids.get(target_node_id)
                if not target_id:
                    continue
                target_node = next(
                    item for item in flow_nodes if item["id"] == target_node_id
                )
                target_pin = next(
                    (
                        item
                        for item in target_node.get("pins", [])
                        if item.get("id") == link.get("pin_id")
                    ),
                    {},
                )
                connections.append(
                    {
                        "from": f"{node_ids[native_node['id']]}.{pin.get('name', '')}",
                        "to": f"{target_id}.{target_pin.get('name', '')}",
                    }
                )

    return {
        "name": graph.get("name", ""),
        "kind": graph.get("kind", ""),
        "nodes": nodes,
        "connections": connections,
    }


def _compact_state_machine(graph: dict[str, Any]) -> dict[str, Any]:
    states = []
    aliases = []
    transitions = []
    entry = None

    for native_node in graph.get("nodes", []):
        operation = native_node.get("operation", {})
        kind = operation.get("kind")
        if kind == "state":
            state = {"name": operation.get("state", native_node.get("title", ""))}
            if operation.get("always_reset_on_entry"):
                state["always_reset_on_entry"] = True
            states.append(state)
        elif kind == "state_alias":
            aliases.append(
                {
                    "name": operation.get("alias", native_node.get("title", "")),
                    "states": operation.get("states", []),
                    "global": operation.get("global", False),
                }
            )
        elif kind == "state_entry":
            for pin in native_node.get("pins", []):
                if pin.get("direction") == "output" and pin.get("links"):
                    target_id = pin["links"][0].get("node_id")
                    target = next(
                        (node for node in graph.get("nodes", []) if node.get("id") == target_id),
                        {},
                    )
                    entry = target.get("operation", {}).get("state", target.get("title"))
                    break
        elif kind == "state_transition":
            transition = {
                key: operation[key]
                for key in (
                    "from",
                    "to",
                    "priority",
                    "crossfade_duration",
                    "blend_mode",
                    "bidirectional",
                    "disabled",
                    "automatic_rule",
                    "automatic_rule_trigger_time",
                    "min_time_before_reentry",
                    "shared_rule",
                )
                if key in operation
            }
            rule_graph = operation.get("rule_graph")
            if rule_graph:
                transition["rule"] = _compact_graph(rule_graph) or {
                    "name": rule_graph.get("name", ""),
                    "kind": "transition_rule",
                    "nodes": [],
                    "connections": [],
                }
            transitions.append(transition)

    result = {
        "name": graph.get("name", ""),
        "kind": "state_machine",
        "states": states,
        "transitions": transitions,
    }
    if entry:
        result["entry_state"] = entry
    if aliases:
        result["aliases"] = aliases
    return result


def compact_blueprint_graphs(result: dict[str, Any]) -> dict[str, Any]:
    """Compact graph detail while preserving the inspection envelope."""
    adapted = deepcopy(result)
    inspection = adapted.get("inspection", {})
    data = inspection.get("data", {})

    if "graphs" in data:
        data["graphs"] = [
            compact
            for graph in data["graphs"]
            if (compact := _compact_graph(graph)) is not None
        ]
    elif "nodes" in data:
        compact = (
            _compact_state_machine(data)
            if data.get("kind") == "state_machine"
            else _compact_graph(data)
        )
        inspection["data"] = compact or {
            "name": data.get("name", ""),
            "kind": data.get("kind", ""),
            "nodes": [],
            "connections": [],
        }
    return adapted
