"""Convert native Blueprint graph data into concise agent-facing logic."""

from __future__ import annotations

from copy import deepcopy
from typing import Any


def _compact_graph(graph: dict[str, Any]) -> dict[str, Any] | None:
    native_nodes = graph.get("nodes", [])
    flow_nodes = [
        node
        for node in native_nodes
        if any(pin.get("links") for pin in node.get("pins", []))
    ]
    if not flow_nodes:
        return None

    node_ids = {node["id"]: f"n{index}" for index, node in enumerate(flow_nodes, 1)}
    nodes = []
    connections = []

    for native_node in flow_nodes:
        operation = native_node.get("operation", {})
        node = {
            "id": node_ids[native_node["id"]],
            "name": native_node.get("title", ""),
            "kind": operation.get("kind", "event"),
        }
        for field in ("function", "owner", "variable"):
            if operation.get(field):
                node[field] = operation[field]

        inputs = {}
        for pin in native_node.get("pins", []):
            if (
                pin.get("direction") == "input"
                and not pin.get("links")
                and not pin.get("hidden")
                and not pin.get("default_matches_autogenerated", True)
            ):
                value = (
                    pin.get("default_value")
                    or pin.get("default_object")
                    or pin.get("default_text")
                )
                if value:
                    inputs[pin.get("name", "")] = value
        if inputs:
            node["inputs"] = inputs
        nodes.append(node)

        for pin in native_node.get("pins", []):
            if pin.get("direction") != "output":
                continue
            for link in pin.get("links", []):
                target_node_id = link.get("node_id")
                target_id = node_ids.get(target_node_id)
                if not target_id:
                    continue
                target_node = next(
                    item for item in flow_nodes if item["id"] == target_node_id
                )
                target_pin = next(
                    (
                        item
                        for item in target_node.get("pins", [])
                        if item.get("id") == link.get("pin_id")
                    ),
                    {},
                )
                connections.append(
                    {
                        "from": f"{node_ids[native_node['id']]}.{pin.get('name', '')}",
                        "to": f"{target_id}.{target_pin.get('name', '')}",
                    }
                )

    return {
        "name": graph.get("name", ""),
        "kind": graph.get("kind", ""),
        "nodes": nodes,
        "connections": connections,
    }


def compact_blueprint_graphs(result: dict[str, Any]) -> dict[str, Any]:
    """Compact graph detail while preserving the inspection envelope."""
    adapted = deepcopy(result)
    inspection = adapted.get("inspection", {})
    data = inspection.get("data", {})

    if "graphs" in data:
        data["graphs"] = [
            compact
            for graph in data["graphs"]
            if (compact := _compact_graph(graph)) is not None
        ]
    elif "nodes" in data:
        compact = _compact_graph(data)
        inspection["data"] = compact or {
            "name": data.get("name", ""),
            "kind": data.get("kind", ""),
            "nodes": [],
            "connections": [],
        }
    return adapted
